### PR TITLE
fix(threads): xtensa: enable saving/restoring float regs

### PR DESCRIPTION
**Pull request by kaspar030**
# Description

... seems like something we want. `esp-wifi` also enables this.

## Change checklist

- [x] I have cleaned up my commit history and squashed fixup commits.
- [x] I have followed the [Coding Conventions](https://future-proof-iot.github.io/RIOT-rs/dev/docs/book/coding-conventions.html).
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by elenaf9** [comment]
Does this impact context switching performance? Because now on each context switch the 15 float registers need to be saved/ restored as well.

**Comment by kaspar030** [comment]
> Does this impact context switching performance? Because now on each context switch the 15 float registers need to be saved/ restored as well.

It probably does. But if we don't save them, they're potentially garbled after a context switch ...

**Comment by elenaf9** [comment]
> But if we don't save them, they're potentially garbled after a context switch

If the feature isn't enabled, the registers aren't "there" from a user perspective, and as soon as they are in the Trapframe we save them because we always switch the whole trapframe.
I was just wondering if we should feature-gate it in case floats aren't needed. And if esp-wifi still enables them than that's not a problem.

**Comment by kaspar030** [comment]
> So IMO users that need floating point operations can just enable it and it will work with our implementation (also thanks to [0e84775](https://github.com/ariel-os/ariel-os/commit/0e847753b0324274046371dfd7d69b8a98c99365)). No need for us to enable it?

Agreed.

**Comment by kaspar030** [comment]
For anyone watching: #665 now enables this regardless of `esp-wifi` being used or not.

**Pull request closed without merging**
